name: publish to Azure

on:
    push:
        branches: [ main ]
    workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.x'
  AZURE_RESOURCE_GROUP: dev-marco
  AZURE_WEBAPP_NAME: wa-aspnet-core-ci-demo
  AZURE_WEBAPP_PACKAGE_PATH: 'AspNetCoreSample'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish app
        run: |
          dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/AspNetCoreSample.csproj \
            --configuration Release \
            --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy infrastructure (Bicep)
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ./infra/main.bicep
          parameters: ./infra/main.bicepparam

      - name: Deploy web app
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish
